@baseUrl = http://localhost:3000

### 1. Registrar al Enfermero Martín Torres (De la HU 1.1 de Enfermería)
POST {{baseUrl}}/iam/register
Content-Type: application/json

{
  "fullName": "Martín Torres",
  "email": "martin.torres@hospital.com",
  "passwordPlain": "enfermeria123",
  "role": "NURSE"
}

### 2. Registrar un Recepcionista (Para Admisión)
POST {{baseUrl}}/iam/register
Content-Type: application/json

{
  "fullName": "Recepcionista Guardia",
  "email": "recepcion@hospital.com",
  "passwordPlain": "recepcion123",
  "role": "RECEPTIONIST"
}

### 3. Hacer Login y obtener el JWT
# @name loginNurse
POST {{baseUrl}}/iam/login
Content-Type: application/json

{
  "email": "martin.torres@hospital.com",
  "passwordPlain": "enfermeria123"
}